#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/momokobd
#    username: root
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#server:
#  port: 5000
#
##Google
#gmail:
#  client:
#    clientId: 720469847940-k8urpge03m9cn055mhi4mae4nn1p843m.apps.googleusercontent.com
#    clientSecret: jgwe1NMipdo79Mfwkjd08WiW
#    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    clientAuthenticationScheme: query
#    scope: profile email
#  resource:
#    userInfoUri: https://www.googleapis.com/plus/v1/people/me
#    preferTokenInfo: false
#
#
#facebook:
#  client:
#    clientId: 1932678757049258
#    clientSecret: 5631874010ff42582ee3bf7a642bec6a
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
#
#github:
#  client:
#    clientId: bd1c0a783ccdd1c9b9e4
#    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user
#
##facebook:
##  client:
##    clientId:
##    clientSecret:
##    accessTokenUri: https://graph.facebook.com/oauth/access_token
##    userAuthorizationUri: https://www.facebook.com/dialog/oauth
##    tokenName: oauth_token
##    authenticationScheme: query
##    clientAuthenticationScheme: form
##  resource:
##    userInfoUri: https://graph.facebook.com/me
#
##Facebook
##facebook:
##  client:
##    clientId: 1932678757049258
##    clientSecret: 5631874010ff42582ee3bf7a642bec6a
##    accessTokenUri: https://graph.facebook.com/oauth/access_token
##    userAuthorizationUri: https://www.facebook.com/dialog/oauth
##    tokenName: oauth_token
##    authenticationScheme: query
##    clientAuthenticationScheme: form
##  resource:
##    userInfoUri: https://graph.facebook.com/me
#
##AuthoritationServer
#
#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#
#
#logging:
#  level:
#    org:
#      springframework:
#        security: INFO
#      hibernate:
#        type: INFO
#        SQL: INFO
#    root: INFO
#
##momoko properties
#
#momoko-configuracion:
#  es-servidor-local: true
#  imagen-default: imagenes-destacadas/generica-libreria.jpg
#  directorios:
#    remote:
#      urlSitemap: http://momoko.local
#      urlFiles: http://momoko.local/images
#      urlTemplates: http://momoko.local/templates
#      urlImages: http://momoko.local/images/
#      urlUpload: http://momoko.local/
#    local:
#      urlSitemap: D:\XAMPP\htdocs\momoko
#      urlFiles: D:\XAMPP\htdocs\momoko\images
#      urlTemplates: D:\XAMPP\htdocs\momoko\templates
#      urlImages: http://momoko.local/images/
#      urlUpload: http://momoko.local/
